feat(Android): Added tokenized gradients
VKCOM/vkui-tokens pull request #1059
Opened 2024-09-09 16:47 UTC by qurle

Упростил описание градиентов в теме Android, чтобы разрабы могли сами их парсить и привязывать к внутренним токенам вместо «плоских цветов».

struct.json до:
```
"gradient": {
	"gradientBlack": "rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.02) 15%, rgba(0, 0, 0, 0.08) 30%, rgba(0, 0, 0, 0.32) 70%, rgba(0, 0, 0, 0.38) 85%, rgba(0, 0, 0, 0.4) 100%",
	"gradientWhite": "rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.05) 15%, rgba(255, 255, 255, 0.2) 30%, rgba(255, 255, 255, 0.8) 70%, rgba(255, 255, 255, 0.95) 85%, rgba(255, 255, 255, 1) 100%",
	"gradientTint": "rgba(249, 249, 249, 0) 0%, rgba(249, 249, 249, 0.05) 15%, rgba(249, 249, 249, 0.2) 30%, rgba(249, 249, 249, 0.8) 70%, rgba(249, 249, 249, 0.95) 85%, rgba(249, 249, 249, 1) 100%",
	"gradient": "rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.05) 15%, rgba(255, 255, 255, 0.2) 30%, rgba(255, 255, 255, 0.8) 70%, rgba(255, 255, 255, 0.95) 85%, rgba(255, 255, 255, 1) 100%"
},
```
struct.json после:
```
"gradient": {
	"gradientBlack": "#00000060, transparent",
	"gradientWhite": "#FFFFFF, transparent",
	"gradientTint": "colorBackgroundTertiary, transparent",
	"gradient": "colorBackgroundContent, transparent"
},
```

2024-09-11 15:04 UTC, 8coon requested changes

2024-09-11 15:04 UTC, 8coon commented on src/themeDescriptions/themes/vkontakteAndroid/index.ts
> +	gradient: 'colorBackgroundContent, transparent',
Если оставить так, то при сборке css получится битый токен. Кажется, нужно обернуть их в var(-- )

2024-09-11 15:36 UTC, qurle commented on src/themeDescriptions/themes/vkontakteAndroid/index.ts
> +	gradient: 'colorBackgroundContent, transparent',
Типа `var(--color_background_content)`?
А есть какое-то более изящное решение, чтобы передать разрабу градиент с именем токена?

2024-09-11 16:38 UTC, qurle commented on src/themeDescriptions/themes/vkontakteAndroid/index.ts
> +	gradient: 'colorBackgroundContent, transparent',
Мб просто добавить новые переменные, из которых разраб будет собирать градиенты 🤔

2024-09-13 12:41 UTC, 8coon commented on src/themeDescriptions/themes/vkontakteAndroid/index.ts
> +	gradient: 'colorBackgroundContent, transparent',
Если var(--color_background_content) по каким-то причинам не подходит, то в целом можно новые токены тогда завести

А почему вариант с var не нравится?

2024-09-13 14:01 UTC, qurle commented on src/themeDescriptions/themes/vkontakteAndroid/index.ts
> +	gradient: 'colorBackgroundContent, transparent',
> @8coon  
А почему вариант с var не нравится?

Потому что у нас будут CSS-переменные в JSON-файле для мобильных разработчиков. Не очень кросс-платформенно)

2024-09-13 15:01 UTC, 8coon commented on src/themeDescriptions/themes/vkontakteAndroid/index.ts
> +	gradient: 'colorBackgroundContent, transparent',
А если тогда добавить пост-процессинг этих значений и добалять var(-- только при сборке css-файлов?

2024-09-13 15:09 UTC, qurle commented on src/themeDescriptions/themes/vkontakteAndroid/index.ts
> +	gradient: 'colorBackgroundContent, transparent',
Хочется наоборот в JSON засунуть эти алиасы (не в виде CSS), чтобы у разраба были не только сырые цвета. Если есть идеи, как это запостпроцессить, буду рад. 

Если идей нет, то будем локально решать.

2024-10-15 16:20 UTC, 8coon approved these changes

2024-10-15 16:25 UTC, merged