Next
VKCOM/vkui-tokens pull request #1085
Opened 2024-10-15 16:49 UTC by 8coon

Перед отправкой этого реквеста на ревью убедитесь, что:

- в вашей ветке работает сборка (`npm run build:local`),
- в вашей ветке проходят тесты (`npm test`),
- в вашей ветке проходит линтер (`npm run lint`), некоторые ошибки можно автоматически поправить с помощью `npm run lint:fix`,
- покрытие тестов не ниже минимального значения,
- если вы вносите изменения в задокументированные части библиотеки,
  ваш pull request содержит обновления документации,
- если вы вносите изменения в сами токены, вы
  согласовали их с дизайнерами.

[Подробнее о внесении изменений в репозиторий токенов](https://github.com/VKCOM/vkui-tokens/blob/master/CONTRIBUTING.md)

2024-10-15 17:05 UTC, qurle requested changes
Если это следующая версия, добавь пж #1075 и #1083

2024-10-15 18:49 UTC, qurle requested changes
Спасибо большое!
Добавь ещё плиз #1087 и посмотри #1088, если не затруднит (я не справился с тайпскриптом)

2024-10-16 07:32 UTC, se-fedorov submitted a review, later dismissed

2024-10-16 11:58 UTC, qurle approved these changes
✨

2024-10-16 12:22 UTC, Sarafa2n approved these changes

2024-10-16 12:41 UTC, merged