Docs page vkui tokens
VKCOM/vkui-tokens pull request #260
Opened 2022-10-21 12:48 UTC by mrzhov

Перед отправкой этого реквеста на ревью убедитесь, что:
* в вашей ветке работает сборка (`npm run build:local`),
* в вашей ветке проходят тесты (`npm test`),
* в вашей ветке проходит линтер (`npm run lint`), некоторые ошибки можно автоматически поправить с помощью `npm run lint:fix`,
* покрытие тестов не ниже минимального значения,
* если вы вносите изменения в задокументированные части библиотеки,
  ваш pull request содержит обновления документации,
* если вы вносите изменения в сами токены, вы
  согласовали их с дизайнерами.

[Подробнее о внесении изменений в репозиторий токенов](https://github.com/VKCOM/vkui-tokens/blob/master/CONTRIBUTING.md)

2022-10-24 12:00 UTC, 8coon commented
![image](https://user-images.githubusercontent.com/12988120/197520516-eec6cd09-f3e4-4c37-8488-9144f2e1f8b9.png)

Кажется, regular и compact оказались перепутаны местами
regular -- это стили для мобильных устройств и размеры больше
compact -- это стили для текстопа и размеры меньше (и ещё их иногда нет)

Надо поправить, и задать атрибут title у переключашек в regular/compact, чтобы было понятно, что есть что.

2022-10-24 12:00 UTC, 8coon requested changes

2022-10-24 12:02 UTC, 8coon commented
Ещё там тесты свалились:

```
Test suite failed to run

Unable to load the module "babel-jest". Using "babel-jest" requires this package to be installed. To fix it:
        ↳ install "babel-jest": `npm i -D babel-jest` (or `yarn add --dev babel-jest`)
```

Надо починить

2022-10-24 16:34 UTC, mrzhov commented on .eslintrc.js
> +		'no-use-before-define': 'off',
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/64151608/197578367-a5c5643f-e308-47e7-aaa7-4657b50321b7.png">

2022-10-24 18:18 UTC, 8coon commented
Тесты ругаются теперь что coverage упал. Кажется, это из-за нового кода, который собирает jsonки тем вместе. Напиши плиз на него юнит, а то и правда можно что-то сломать и узнать об этом только когда дока не соберётся

2022-10-25 15:25 UTC, 8coon approved these changes

2022-10-25 15:25 UTC, merged