Тема проекта Pulse
VKCOM/vkui-tokens pull request #267
Opened 2022-10-27 18:27 UTC by petermihailov

Перед отправкой этого реквеста на ревью убедитесь, что:
* в вашей ветке работает сборка (`npm run build:local`),
* в вашей ветке проходят тесты (`npm test`),
* в вашей ветке проходит линтер (`npm run lint`), некоторые ошибки можно автоматически поправить с помощью `npm run lint:fix`,
* покрытие тестов не ниже минимального значения,
* если вы вносите изменения в задокументированные части библиотеки,
  ваш pull request содержит обновления документации,
* если вы вносите изменения в сами токены, вы
  согласовали их с дизайнерами.

[Подробнее о внесении изменений в репозиторий токенов](https://github.com/VKCOM/vkui-tokens/blob/master/CONTRIBUTING.md)

2022-10-28 14:26 UTC, petermihailov commented on src/interfaces/themes/pulse/index.ts
> +export interface ThemePulseCssVars extends ThemeCssVars<ThemePulse> {}
У нас ещё не все макеты перешли на токены, и в каких-то случаях разработчики смотрят либо какой токен подойдет по смыслу, либо (в худшем случае) какой токен больше подойдет по свойствам. А дизайнеры используют ограниченный набор цветов, размеров и отступов. И поинт в том чтобы разработчики использовали только то, что есть у дизайнера чтобы минимизировать ошибки

2022-10-31 08:56 UTC, petermihailov commented on src/interfaces/themes/pulse/index.ts
> +	colorWhiteBlueAlpha: ColorDescription;
поправил

2022-11-01 14:39 UTC, 8coon requested changes

2022-11-01 14:39 UTC, 8coon commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundErrorAlpha: 'rgba(237, 10, 52, 0.1)',
Кажется, для этого есть colorBackgroundNegativeTint

2022-11-01 14:39 UTC, 8coon commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundInfoAlpha: 'rgba(0, 95, 249, 0.1)',
Почему не colorBackgroundAccentTint?

2022-11-01 14:39 UTC, 8coon commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundPositiveAlpha: 'rgba(13, 194, 104, 0.1)',
Почему не colorBackgroundPositiveTint?

2022-11-01 14:39 UTC, 8coon commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundWarningAlpha: 'rgba(255, 158, 0, 0.1)',
Для этого кажется есть colorBackgroundWarningTint либо colorBackgroundWarningTintAlpha

2022-11-01 14:39 UTC, 8coon commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorStateHoverAlpha: 'rgba(0, 16, 61, 0.04)',
Все цвета для hover и active-стейтов генерируются автоматически для всех токенов, если нужно сгенерировать цвета для какого-то отдельного блока, то нужно заводить токен под этот блок, например:

`pulseColorMyBlock: 'rgba(0, 16, 61, 0.08)'`

Также можно перебить цвета стейтов, сгенерированные алгоритмом, и задать свои руками:

```
pulseColorMyBlock: {
    normal: 'rgba(0, 16, 61, 0.02)',
    hover: 'rgba(0, 16, 61, 0.04)',
    active: 'rgba(226, 236, 255, 0.9)'
}
```

2022-11-01 18:19 UTC, petermihailov commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundErrorAlpha: 'rgba(237, 10, 52, 0.1)',
насколько я понял тинты не поддерживают альфа-канал судя по тестам
https://github.com/VKCOM/vkui-tokens/blob/master/src/lint/rules/alphaMismatch.ts#L25

2022-11-17 09:46 UTC, petermihailov commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundWarningAlpha: 'rgba(255, 158, 0, 0.1)',
в теме `paradigm` действительно есть `colorBackgroundWarningTintAlpha`, однако будет странно использовать другой нейминг для одного свойства из группы:  
```
pulseColorBackgroundErrorAlpha, 
pulseColorBackgroundInfoAlpha, 
pulseColorBackgroundPositiveAlpha, 
colorBackgroundWarningTintAlpha
```

2022-11-17 09:59 UTC, petermihailov commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundInfoAlpha: 'rgba(0, 95, 249, 0.1)',
все как в прошлом комментарии: тинты не поддерживают альфа-канал, и ниже по коду в `pulseColorBackgroundPositiveAlpha` тоже по этой причине

2022-11-17 09:59 UTC, petermihailov commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorStateHoverAlpha: 'rgba(0, 16, 61, 0.04)',
исправлено

2022-11-17 11:28 UTC, 8coon commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundWarningAlpha: 'rgba(255, 158, 0, 0.1)',
Но всё-таки не стоит дублировать токены с одинаковой семантикой. Возможно, стоит эти токены вообще вынести в paradigm и сделать базовыми для всех тем (colorBackground.*TintAlpha) @Fliqle

2022-11-17 11:29 UTC, 8coon commented on src/interfaces/themes/pulse/index.ts
> +}
Префикс pulse нужно добавить всем токенам, которых нет в базовой теме

2022-11-17 13:27 UTC, petermihailov commented on src/interfaces/themes/pulse/index.ts
> +}
fixed

2022-11-17 13:39 UTC, Fliqle commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundWarningAlpha: 'rgba(255, 158, 0, 0.1)',
А у нас эти токены есть в paradigm

2022-11-17 13:42 UTC, 8coon commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundWarningAlpha: 'rgba(255, 158, 0, 0.1)',
Вообще Background Tint у нас есть разные, мб их можно и использовать?
![image](https://user-images.githubusercontent.com/12988120/202461946-9fbd3813-d01b-44b7-a31f-c2598a66c4a0.png)

2022-11-17 13:49 UTC, Fliqle commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundWarningAlpha: 'rgba(255, 158, 0, 0.1)',
А пусть дизайнер кто инициировал ко мне зайдет

2022-11-17 14:14 UTC, petermihailov commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundWarningAlpha: 'rgba(255, 158, 0, 0.1)',
да, я очень извиняюсь, не от той темы наследовался. Все цвета есть кроме Info, его добавил с префиксом `pulse`

2022-11-17 14:36 UTC, petermihailov commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundWarningAlpha: 'rgba(255, 158, 0, 0.1)',
да, я очень извиняюсь, не от той темы наследовался. Поговорил с дизайнером, взяли 4 токена из `paradigm`:  
```
colorBackgroundAccentTintAlpha
colorBackgroundNegativeTintAlpha
colorBackgroundPositiveTintAlpha
colorBackgroundWarningTintAlpha
```

2022-11-21 09:04 UTC, petermihailov commented on src/themeDescriptions/themes/pulse/index.ts
> +		pulseColorBackgroundPositiveAlpha: 'rgba(13, 194, 104, 0.1)',
исправлено

2022-11-28 13:42 UTC, 8coon approved these changes

2022-11-30 14:14 UTC, merged