feat(vk base): use `VK Sans Display` for `fontFamilyAccent`
VKCOM/vkui-tokens pull request #396
Opened 2023-02-08 16:11 UTC by inomdzhon

## Описание

- Добавил возможость использовать [jsdoc {@link}](https://jsdoc.app/tags-inline-link.html).
- Удалил копипаст значений типографики в `themeDescriptions/themes/vkCom` – вытаскиваю из базовой `lightTheme`.
- Создал папку `@/shared/constants`, чтобы шарить константы.
- Перебиваю базовый **jsdoc** для `fontFamilyAccent` в `src/interfaces/themes/vkBase/index.ts`.

---

- close #376

---

Перед отправкой этого реквеста на ревью убедитесь, что:

- в вашей ветке работает сборка (`npm run build:local`),
- в вашей ветке проходят тесты (`npm test`),
- в вашей ветке проходит линтер (`npm run lint`), некоторые ошибки можно автоматически поправить с помощью `npm run lint:fix`,
- покрытие тестов не ниже минимального значения,
- если вы вносите изменения в задокументированные части библиотеки,
  ваш pull request содержит обновления документации,
- если вы вносите изменения в сами токены, вы
  согласовали их с дизайнерами.

[Подробнее о внесении изменений в репозиторий токенов](https://github.com/VKCOM/vkui-tokens/blob/master/CONTRIBUTING.md)

2023-02-09 11:06 UTC, 8coon requested changes

2023-02-09 11:06 UTC, 8coon commented on src/themeDescriptions/themes/vkCom/index.ts
> +			fontWeight: Number(lightTheme.fontWeightAccent2),
А можешь рассказать, зачем здесь явное приведение типа?

2023-02-09 12:19 UTC, inomdzhon commented on src/themeDescriptions/themes/vkCom/index.ts
> +			fontWeight: Number(lightTheme.fontWeightAccent2),
@8coon TS неправильно выкупает типы :(

Считает, что `lightTheme.fontFamilyAccent` возвращает `Property.FontFamily | ((theme: ThemeGeneral) => Property.FontFamily)`

<img width="747" alt="image" src="https://user-images.githubusercontent.com/5850354/217806427-f7c47a97-9a50-4c80-8bbf-a8ec79929013.png">

Но вообще из-за TS приводить к типам такое себе, поправил на проверку, что не функция (запушил)

А вообще там может быть функция?

2023-02-13 09:54 UTC, Fliqle commented
А что с этим? Почему тесты не проходят?

2023-02-15 17:26 UTC, inomdzhon commented
см. https://github.com/VKCOM/vkui-tokens/issues/376#issuecomment-1431738454

2023-02-15 17:26 UTC, closed without merging