feat: add vkontakte themes
VKCOM/vkui-tokens pull request #481
Opened 2023-04-07 07:26 UTC by SevereCloud

Добавляем темы для ВКонтакте

2023-04-07 13:50 UTC, Zaycevq submitted a review, later dismissed
👍🏽

2023-04-10 10:44 UTC, 8coon requested changes

2023-04-10 10:44 UTC, 8coon commented on src/themeDescriptions/themes/vkontakteAndroid/index.ts
> +	colorSnippetBorderAlpha: 'rgba(0, 0, 0, 0.15)',
Это к сожалению нигде явно не прописано, но локальные токены у нас во всех темах заводятся с префиксом имени базовой темы. Для октавиуса локальные токены все начинаются с octavius (типа octaviusColorWhitelineBackground), соответственно тут должны начинаться с vkontakte

Это нужно чтобы потом в коде быстро и наглядно понимать, какой код можно переносить между проектами, а в каком нужно поменять токены.

2023-04-10 13:44 UTC, SevereCloud commented on src/themeDescriptions/themes/vkontakteAndroid/index.ts
> +	colorSnippetBorderAlpha: 'rgba(0, 0, 0, 0.15)',
Добавил

2023-04-10 13:47 UTC, 8coon approved these changes

2023-04-10 14:15 UTC, Zaycevq approved these changes
👍🏽

2023-04-12 13:53 UTC, merged