Update & New Tokens for vkBase / vkCom
VKCOM/vkui-tokens pull request #569
Opened 2023-08-16 16:23 UTC by Zaycevq

Добавлен токен colorBackgroundContrastThemed который будем использовать для фона Табов. 

Текущий токен colorBackgroundModal сливается на некоторых кейсах

- - - -
Изменено расположение Button токенов цвета, унесены в Other, пока не используем (нашлось решение лучше)

- - - -
Изменены токены для vkCom:
· colorBackgroundModal
· colorBackgroundSecondaryAlpha (другой оттенок, на котором лучше читается текст в кнопках на vkCom)
· colorText/Icon/StrokeAccentTheme (чуть более тёмный, для лучшей читаемости в кнопках vkCom)

2023-08-17 09:35 UTC, Sarafa2n requested changes

2023-08-17 09:35 UTC, Sarafa2n commented on src/interfaces/general/colors/index.ts
> -
А зачем переносить ?

2023-08-17 12:59 UTC, Zaycevq commented on src/interfaces/general/colors/index.ts
> -
> А зачем переносить ?

Что бы стиль нейминга сохранить, сначала компонент, потом его свойство. Так мы делали для других токенов в Other которые нацелены на конкретный компонент и по хорошему для этих токенов нужно так же.

2023-08-23 16:29 UTC, Sarafa2n approved these changes

2023-08-25 09:58 UTC, merged