feat: Added accessibility theme
VKCOM/vkui-tokens pull request #946
Opened 2024-06-28 15:43 UTC by qurle

Добавили тему с повышенной контрастностью для вторичных и третичных цветов

<img width="560" src="https://github.com/VKCOM/vkui-tokens/assets/32414396/f0414b9d-282b-4a3a-a7d9-73cd033674ed"/>

2024-07-01 13:42 UTC, Sarafa2n requested changes

2024-07-01 13:42 UTC, Sarafa2n commented on src/themeDescriptions/themes/vkIOS/index.ts
> -	...darkColors,
а точно убираем темную тему в ios ?

2024-07-01 14:01 UTC, qurle commented on src/themeDescriptions/themes/vkIOS/index.ts
> -	...darkColors,
Упс. Пофиксил ⚡️ 45dddbb39747e03d965f092660f636e56feefc72

2024-07-04 10:06 UTC, 8coon approved these changes

2024-07-04 10:07 UTC, merged